import{writeFileSync}from'node:fs';
const ap=String.fromCharCode(8217),em=String.fromCharCode(8212);
const lines=[];const a=s=>lines.push(s);
a('# Evaluation: Brillio '+em+' AI Program Director (Banking)');
a('');
a('**Date:** 2026-04-13');
a('**Archetype:** AI Transformation Lead / Enterprise Technology Strategy');
a('**Score:** 3.7/5');
a('**URL:** https://jobs.lever.co/brillio-2/5c2c3774-155a-4cbd-b1ad-c84f7623e47c/');
a('**PDF:** output/cv-daniel-levine-brillio-ai-program-director-2026-04-13.pdf');
a('**Verification:** unconfirmed (JD provided manually)');
a('');a('---');a('');
a('## Block A '+em+' Role Summary');
a('');a('| Field | Detail |');a('|-------|--------|');
a('| Company | Brillio (enterprise AI and digital transformation consultancy) |');
a('| Title | AI Program Director |');
a('| Location | Not specified '+em+' likely client-embedded; travel expected |');
a('| Salary | Not disclosed |');
a('| Employment Type | Full-time |');
a('| Client Context | Major banking client '+em+' Data Platform Modernization (Snowflake on AWS) + AI Platform and Use Case Delivery |');
a('');a('---');a('');
a('## Block B '+em+' What the Role Actually Is');
a('');
a('This is a senior program leadership role embedded in a Brillio client engagement at a leading U.S. banking institution. Functionally, it operates as Chief of Staff for a major multi-workstream enterprise transformation '+em+' coordinating across governance, architecture, build, and operations teams while serving as the single senior point of visibility for executive stakeholders on both the Brillio and client sides.');
a('');
a('The program has two parallel tracks:');
a('');
a('1. **Data Platform Modernization** '+em+' migration to Snowflake on AWS; enterprise-scale data architecture overhaul');
a('2. **AI Platform and Use Case Delivery** '+em+' building and delivering AI/GenAI capabilities on top of the modernized data foundation');
a('');
a('The role requires end-to-end ownership of the program roadmap, milestone discipline, risk management, and executive stakeholder visibility. It sits at the intersection of program delivery governance and executive client management '+em+' more Strategic Program Director than hands-on technical architect. The JD explicitly describes it as the role of someone who connects vision with execution and acts as the face of the program.');
a('');
a('**About Brillio:** Fast-growing digital transformation and enterprise AI consultancy (~6,000 employees). Positions itself as the Enterprise AI Accelerator serving Fortune 1000 clients. Core practice areas: AI, data engineering, cloud, customer experience. Revenue reportedly growing ~60% YoY. Recently launched ADAM (Agentic Data and Application Management) agentic platform. Serious player in the enterprise AI delivery space '+em+' not hype-driven, oriented to repeatable delivery outcomes.');
a('');a('---');a('');
a('## Block C '+em+' Fit Analysis');
a('');a('### Strengths');a('');
a('**Program leadership at enterprise scale '+em+' direct match.**');
a('The core demand '+em+' owning end-to-end program oversight across multiple workstreams, managing stakeholder visibility, and connecting vision to execution '+em+' maps directly to Daniel'+ap+'s 14-year CTO track record at MMI. He built and led a technology organization of 35+ direct staff (75+ including extended and global vendor teams), managed $15M+ annual operating budgets, and led multi-year transformation programs from design through zero-disruption go-live. He has done this work '+em+' not adjacent to it.');
a('');
a('**Transformation coordination '+em+' demonstrated model.**');
a('The JD describes exactly what Daniel built at MMI: coordinating across architecture, build, and operations teams while maintaining alignment to senior leadership priorities. His ePMO creation (25% improvement in project budget/time adherence) and doubled development throughput demonstrate the execution discipline this role demands. He has also done this in a regulated financial services environment '+em+' CARD Act compliance, HIPAA, PCI-DSS '+em+' which is directionally relevant to a banking client.');
a('');
a('**Executive stakeholder interface '+em+' high confidence.**');
a('Act as the primary interface for senior stakeholders is a description of Daniel'+ap+'s career, not a stretch goal. He functioned as the executive technology voice for an organization for 14 years: board-level financial reporting, budget management, cross-functional executive partnership at the C-suite. Being the single point of visibility to senior leadership is his natural operating mode.');
a('');
a('**AI and data platform context '+em+' reasonable match.**');
a('Daniel'+ap+'s background includes AI strategy development, enterprise AI adoption framing, and building structured evaluation frameworks for AI architectures (current consulting work). His data platform foundation is at strategic and governance level '+em+' not Snowflake specifically '+em+' but the role is program governance, not Snowflake architecture. He needs to credibly manage people who know Snowflake, not be one of them.');
a('');
a('**Consultancy operating model '+em+' current mode.**');
a('Daniel is actively consulting independently on enterprise AI architecture. Moving into a senior client-embedded delivery leadership role at a major consultancy is a natural evolution of that work, not a category change. He understands the dynamics of advising and the client relationship accountability model.');
a('');
a('**Innovation Ethos and Big Picture Thinking '+em+' authentic fit.**');
a('Brillio'+ap+'s stated leadership qualities (Customer Advocacy, Owner'+ap+'s Mindset, Innovation Ethos, Execution with Pace, Big Picture Thinking) align genuinely with Daniel'+ap+'s operating style. He has a published, grounded view of AI '+em+' distinguishes automation from AI, approaches problems context-first, executes with clear accountability. He is not a move-fast-and-hype-things leader, which is consistent with what Brillio says it wants.');
a('');a('### Gaps');a('');
a('**BFSI domain knowledge '+em+' genuine gap.**');
a('The JD explicitly calls out Deep BFSI domain knowledge (banking, regulatory, risk, data ecosystems) as a requirement. Daniel'+ap+'s enterprise background is in consumer financial services (Money Management International '+em+' consumer debt counseling, CARD Act compliance, PCI-DSS, HIPAA) '+em+' not core banking. He understands regulated environments, compliance frameworks, and financial data governance, but banking-specific domain expertise (core banking architecture, risk models, Basel III, DORA, banking data ecosystems) is not in his background. This is the primary fit risk and will surface in interviews. It must be addressed directly, not minimized.');
a('');
a('**Snowflake/AWS hands-on depth.**');
a('Not a blocker for a program director role, but Brillio will likely expect someone who can engage credibly in architectural discussions. Daniel can engage at the governance and strategy level. He is not a Snowflake practitioner and should not claim otherwise.');
a('');
a('**Consulting firm delivery accountability.**');
a('Daniel has operated as an enterprise operator with internal accountability; Brillio is a client-delivery consultancy. Delivery accountability (client satisfaction, billable execution, margin, retention risk, escalation handling) differs from an in-house CTO model. Manageable '+em+' especially given his independent consulting experience '+em+' but worth framing clearly in interviews.');
a('');a('---');a('');
a('## Block D '+em+' Score Summary');
a('');a('| Dimension | Score | Notes |');a('|-----------|-------|-------|');
a('| CV Match | 4.0 | Strong program leadership fit; executive stakeholder interface; transformation coordination; BFSI and Snowflake gaps real but not disqualifying for program governance role |');
a('| North Star | 3.8 | Fits AI Transformation Lead and Enterprise Technology Strategy archetypes; genuine executive scope; consultancy is a natural extension of current trajectory |');
a('| Comp | 3.5 | Undisclosed; senior program director at a consultancy likely $160-220K base; plausibly clears the floor at this engagement level |');
a('| Culture/Mission | 3.8 | Brillio enterprise AI focus, Fortune 1000 client base, and measured (non-hype) positioning match Daniel'+ap+'s worldview; consultancy culture is a reasonable fit |');
a('| Remote/Location | 3.0 | Not specified; client-embedded consulting typically requires presence at client site; travel ambiguity is real |');
a('| **Global** | **3.7** | Solid fit on execution fundamentals; BFSI domain gap and comp ambiguity are the primary variables |');
a('');a('---');a('');
a('## Block E '+em+' Recommendation');
a('');
a('**Apply, with clear eyes on the BFSI gap.**');
a('');
a('The role is a genuine fit for Daniel'+ap+'s executive program leadership capabilities. The core demand '+em+' coordinating a multi-workstream enterprise transformation, managing senior stakeholder relationships, and ensuring execution discipline '+em+' maps directly to 14 years of evidence. The program scope is real (Fortune 1000 bank, dual-track modernization, executive visibility mandate). Title is irrelevant here; the work is the right kind of work.');
a('');
a('**Positioning angle:** Frame this as an enterprise transformation executive who has operated in a highly regulated, multi-site, multi-stakeholder financial services environment (consumer financial services, CARD Act compliance, PCI-DSS, HIPAA) and who has direct experience running this type of platform modernization and AI enablement program. Banking-specific domain can be learned and will be supplemented by Brillio'+ap+'s banking practice resources; program leadership and executive presence cannot be taught.');
a('');
a('**The BFSI response (exact framing):**');
a('> My regulatory environment at MMI was consumer financial services '+em+' CARD Act compliance, PCI-DSS certification maintained over multiple years, HIPAA. The governance discipline, the audit pressure, the stakeholder management in a regulated enterprise '+em+' that context transfers. I would be learning banking-specific nomenclature and data ecosystem details, not the discipline behind regulated program delivery. And I'+ap+'d be doing that learning within a firm that has deep banking practice depth '+em+' which is the right support structure for that learning curve.');
a('');
a('**Before applying:** Clarify whether this is an active, named client engagement (program already underway) or a capacity-building hire for future banking engagements. The distinction affects how immediate and specific the BFSI knowledge requirement will be in the first 90 days.');
a('');
a('**Score: 3.7 '+em+' Apply.** Stronger-than-average on execution fundamentals and executive presence. Domain specificity and comp structure are the primary open questions to resolve in discovery.');
a('');
writeFileSync('reports/060-brillio-2026-04-13.md',lines.join('\n'),'utf8');
console.log('060 written, chars:',lines.join('\n').length);
