import{writeFileSync}from'node:fs';
const ap=String.fromCharCode(8217),em=String.fromCharCode(8212);
const lines=[];const a=s=>lines.push(s);
a('# Evaluation: Koch Engineered Solutions '+em+' IT Architect');
a('');
a('**Date:** 2026-04-13');
a('**Archetype:** Enterprise Technology Strategy (infrastructure-focused IC role)');
a('**Score:** 2.8/5');
a('**URL:** https://koch.avature.net/en_US/careers/JobDetail/178756');
a('**PDF:** NO (score below 3.2 threshold)');
a('**Verification:** unconfirmed (JD provided manually)');
a('');a('---');a('');
a('## Block A '+em+' Role Summary');
a('');a('| Field | Detail |');a('|-------|--------|');
a('| Company | Koch Engineered Solutions (KES), subsidiary of Koch Industries |');
a('| Title | IT Architect |');
a('| Location | Not specified; KES HQ is Wichita, KS area '+em+' likely hybrid or on-site |');
a('| Salary | Not disclosed; IT Architect market rate ~$130-180K |');
a('| Employment Type | Full-time |');
a('| Domain | Infrastructure architecture '+em+' cloud (AWS/Azure), OT/manufacturing, endpoint, network, security |');
a('');a('---');a('');
a('## Block B '+em+' What the Role Actually Is');
a('');
a('This is a senior individual contributor / principal architect role within Koch Engineered Solutions IT infrastructure function. KES is a manufacturing-focused Koch Industries subsidiary, producing filtration systems, heat exchangers, and other engineered materials for industrial markets.');
a('');
a('The role is responsible for defining and executing infrastructure architecture strategy across cloud (AWS/Azure), Operational Technology (OT) and plant control networks, endpoint/compute, storage, network, and security domains. Key responsibilities: define reference architectures and technology roadmaps, lead architecture alternatives analysis, guide on-premises/hybrid/cloud infrastructure design, govern emerging technology adoption, and serve as a senior escalation point for complex infrastructure issues.');
a('');
a('This is NOT a people-management or P&L executive role. It is a principal-level technical architect who influences without direct authority. The JD explicitly requires hands-on design and implementation experience across multiple infrastructure pillars and specific OT/manufacturing systems knowledge as basic qualifications.');
a('');
a('**About Koch Engineered Solutions / Koch Industries:** Koch Industries is one of the largest private companies in the U.S. (~$125B revenue). KES produces engineered materials for industrial applications. Koch has enterprise-scale IT with genuine technology investment, including partnerships with C3.ai and Sema4.ai for AI. The IT function operates at real enterprise scale with a long-termism culture.');
a('');a('---');a('');
a('## Block C '+em+' Fit Analysis');
a('');a('### Strengths');a('');
a('**Cloud architecture strategy '+em+' partial match.**');
a('Daniel has enterprise cloud migration experience: led full migration of all MMI workloads to cloud, has Azure enterprise platform expertise, and has operated as the strategic decision-maker for cloud infrastructure investments. He can engage credibly at the governance and strategy level for cloud architecture discussions and vendor evaluation.');
a('');
a('**Architecture governance and standards '+em+' conceptual match.**');
a('The role includes defining reference architectures, technology roadmaps, and governance models. Daniel built an ePMO, established technology governance frameworks, managed multi-year technology strategy, and evaluated and selected enterprise platforms across ITSM, contact center, analytics, and development tooling. The governance mindset is present, even if the infrastructure depth is not.');
a('');
a('**Cross-functional communication '+em+' strong.**');
a('The JD emphasizes tailoring messages for technical, executive, and non-technical audiences. This is a genuine Daniel strength: 14 years as the executive technology translator, communicating architecture decisions to boards, C-suite peers, and operational teams simultaneously.');
a('');
a('**Koch entrepreneurial culture '+em+' reasonable fit.**');
a('Koch emphasizes intellectual independence, challenging the status quo, and an ownership mindset. These signals align with Daniel'+ap+'s operating model. The private company culture (no quarterly earnings pressure) also aligns with his preference for organizations that take a longer view on technology investment.');
a('');a('### Gaps');a('');
a('**Infrastructure depth '+em+' primary disqualifier.**');
a('The JD explicitly requires hands-on design and implementation experience across multiple infrastructure technology pillars (endpoint, mobility, compute, storage, network, security). Daniel'+ap+'s background is in software development leadership, digital transformation, and AI strategy. His infrastructure exposure is at the governance and vendor-management level: he decided what to buy and who owned it, not how to architect it at the protocol and system level. He is not an infrastructure architect.');
a('');
a('**OT/manufacturing and Plant Control Networks '+em+' no background.**');
a('The JD lists experience with Operational Technology (OT), manufacturing systems, and Plant/Process Control Networks (PCN) as a basic qualification, not a preference. Daniel has zero manufacturing industry exposure and no OT background whatsoever. There is no adjacent experience to bridge from. This is a fundamental requirement mismatch, not a gap that framing can address.');
a('');
a('**Role scope '+em+' IC, not executive.**');
a('This role carries no team ownership, budget authority, or strategic executive mandate. It is a principal architect '+em+' a high-level individual contributor. This is a scope mismatch with Daniel'+ap+'s profile as a three-legged IT executive (people, technology, budget). The JD explicitly frames influence without direct authority as the operating model. Daniel is qualified for roles that carry actual authority.');
a('');
a('**Comp likely below floor.**');
a('IT Architect market rates at a manufacturing subsidiary typically run $130-170K base. Daniel'+ap+'s evaluation floor is $180K. Even at Koch Industries scale, this title at a manufacturing subsidiary is unlikely to reach the target without significant negotiation or senior banding clarification.');
a('');a('---');a('');
a('## Block D '+em+' Score Summary');
a('');a('| Dimension | Score | Notes |');a('|-----------|-------|-------|');
a('| CV Match | 2.5 | No hands-on infrastructure architecture depth; no OT/manufacturing experience; cloud at governance/strategy level only; skills gap is fundamental, not reframeable |');
a('| North Star | 2.0 | IC role with no team ownership, budget authority, or strategic mandate; does not match any of Daniel'+ap+'s executive archetypes regardless of title |');
a('| Comp | 2.5 | Undisclosed; IT Architect at a manufacturing subsidiary likely $130-170K base '+em+' below Daniel'+ap+'s $180K floor |');
a('| Culture/Mission | 3.5 | Koch entrepreneurial culture is a genuine fit; manufacturing domain and infrastructure focus are not particularly compelling for Daniel'+ap+'s trajectory |');
a('| Remote/Location | 3.0 | Location not specified; KES HQ in Wichita KS area '+em+' likely not fully remote; not a preferred market |');
a('| **Global** | **2.8** | Three compounding fundamental gaps: skills, scope, and comp |');
a('');a('---');a('');
a('## Block E '+em+' Recommendation');
a('');
a('**Do not apply.**');
a('');
a('This role has three compounding problems that together make it a poor fit, and none of them are title-related:');
a('');
a('1. **Skills mismatch:** Daniel'+ap+'s background is executive IT leadership, digital transformation, and AI strategy '+em+' not hands-on infrastructure architecture. The role requires deep, practical experience across endpoint, network, compute, storage, security, and OT/manufacturing control systems. That experience is not there, and there is no bridge from his background that makes it credible.');
a('');
a('2. **Scope mismatch:** This is a principal IC architect role. No team. No budget. Influence without authority. Daniel leads organizations '+em+' teams of teams with real P&L accountability. Taking an IC architect role would be a step down in actual scope (not just title), and his 14-year CTO background would likely surface as overqualification in interviews with a predictable departure risk concern.');
a('');
a('3. **Domain mismatch:** OT and Plant Control Network experience is listed as a basic qualification. Manufacturing/industrial control infrastructure is a specialized domain that requires deep, domain-specific expertise. There is no MMI analog, no adjacent experience, and no framing that bridges this gap.');
a('');
a('Note on the title: the instruction not to penalize for title step-down is applied here. The problem is not that the title is IT Architect versus VP or CTO. The problem is that the actual work '+em+' hands-on infrastructure design, OT architecture, multi-pillar systems engineering '+em+' does not align with Daniel'+ap+'s actual skill set at any level. A VP-titled infrastructure architect role at KES would score similarly.');
a('');
a('**Koch Industries is an interesting company at a different scope.** A VP of Technology, Enterprise Architecture (with executive scope), or AI Strategy role at Koch would be worth evaluating. This specific posting is not appropriate.');
a('');
a('**Score: 2.8 '+em+' Do not apply.** Three fundamental, non-reframeable gaps.');
a('');
writeFileSync('reports/061-koch-industries-2026-04-13.md',lines.join('\n'),'utf8');
console.log('061 written, chars:',lines.join('\n').length);
